name: "Build and push to hub.docker.com"

on: [workflow_dispatch]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: yuriikirychuk/documentov:latest,yuriikirychuk/documentov:${GITHUB_REF##*/}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}