name: "Build and push to hub.docker.com"

on:
  push:
    branches:
      - "develop"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get the version
        id: branch_name
        run: echo ::set-output name=SOURCE_TAG::$(echo ${GITHUB_REF##*/})
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yuriikirychuk/documentov:${{ steps.branch_name.outputs.SOURCE_TAG }}
          no-cache: true
          platforms: linux/amd64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
